/*CREAR RESERVACION*/

/*SE CREAN RELAICONES DE PROCEDIMIENTO EN LA MISMA FECHA PARA EL MISMO PACIENTE*/

/*RESERVACION PARA UN PROCEDIMIENTO*/
INSERT INTO Paci_tiene_proc(Cedula, Id_proc, Fecha)
VALUES(12345678, 2, 2023-05-22);